const actionTypes = {
  LOAD_ERROR: 'LOAD_ERROR',
  LOAD_POKEMON_DETAIL: 'LOAD_POKEMON_DETAIL',
  LOAD_POKEMON_MOVE: 'LOAD_POKEMON_MOVE',
  LOAD_POKEMON_ABILITY: 'LOAD_POKEMON_ABILITY',
  UPDATE_SEARCH_STRING: 'UPDATE_SEARCH_STRING',
  CLEAR: 'CLEAR',
  CLEAR_STRING: 'CLEAR_STRING',
};

export default actionTypes;
