const actionTypes = {
  LOAD_ERROR: 'LOAD_ERROR',
  LOAD_POKEMON_DETAIL: 'LOAD_POKEMON_DETAIL',
  LOAD_POKEMON_MOVE: 'LOAD_POKEMON_MOVE',
  LOAD_POKEMON_ABILITY: 'LOAD_POKEMON_ABILITY',
  CLEAR: 'CLEAR',
};

export default actionTypes;
